imports:
    - { resource: 'parameters.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Controller\DefaultController:
        arguments:
            - '@translator'
            - '@App\Library\RemoteClient'
            - '%app.remote.valid_keys%'

    App\Library\RemoteClient:
        arguments:
            - '@cache.app'
            - '@App\Library\RemoteLogger'
            - '%env(TV_IP)%'
            - '%app.remote.protocol.secure%'
            - '%app.remote.port.secure%'
            - '%app.remote.name%'
            - '%kernel.environment%'

    App\Library\RemoteLogger:
        class: Monolog\Logger
        arguments:
            - 'remote'
